# Dependencies
markdown:         kramdown
highlighter:      rouge


collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  pages:
    output: true
    permalink: /:title/

# Setup
title:            BeagleByte
tagline:          'A Jekyll theme'
description:      'A BeagleByte theme for tech topics, tutorials, and more.'
baseurl:          /BeagleByte
url:              http://BeagleByte.github.io

author:
  name:           'BeagelByte'

# Custom vars
version:          0.1.0



