# Dependencies
markdown:         kramdown
highlighter:      rouge

collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  pages:
    output: true
    permalink: /:title/

# Setup
title:            BeagleByte Dev & Sec
tagline:          'A Jekyll theme'
description:      'A BeagleByte theme for tech topics, tutorials, and more.'
keywords:          "Python, Cyber Security, Java, Development, Spring, Spring Boot, Jekyll, Hacking"
baseurl:          /BeagleByte
url:              http://BeagleByte.github.io
author:
  name:           'BeagleByte'


# Custom vars
version:          0.7.9



