# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'A BeagleByte theme for tech topics, tutorials, and more.'
baseurl:          /

author:
  name:           'BeagelByte'
  url:            https://github.com/BeagleByte

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:          https://github.com/BeagleByte/BeagleByte