# Dependencies
markdown:         kramdown
highlighter:      rouge

collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
  pages:
    output: true
    permalink: /:title/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: archive
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'

# Setup
title:            BeagleByte Dev & Sec
tagline:          'A Jekyll theme'
description:      'A BeagleByte theme for tech topics, tutorials, and more.'
keywords:          "Python, Cyber Security, Java, Development, Spring, Spring Boot, Jekyll, Hacking"
baseurl:          /
url:              http://BeagleByte.github.io
author:
  name:           "BeagleByte"


# Custom vars
version:          0.7.9



